version: '3'
services:
  web:
    build:
      context: .
      args:
        VIEW:
        BROWSERIFY:
    image: primo-explore-devenv
    environment:
      VIEW:
      BROWSERIFY:
    ports:
      - 8003:8003
      - 3001:3001
    volumes:
      - ./primo-explore:/app/primo-explore
      - ./packages:/app/packages
